### PR TITLE
adding __init__

### PR DESCRIPTION
**Pull request by mattmahoneyrh**

### CODE REVIEW

**Comment by kialiqeci** [comment]
Build comment file: 
--------------
:red_circle: Jenkins CI: python-rest-test-pr [#8](https://paste.fedoraproject.org/paste/0InJE4~m5Y6NiRNiCsocyw)
  * :red_circle: run-python-rest-tests [#188](https://paste.fedoraproject.org/paste/pJmWBksi-r8ZPagbwLkKkA)
--------------

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Build comment file: 
--------------
:red_circle: Jenkins CI: python-rest-test-pr [#9](https://paste.fedoraproject.org/paste/wkbiXS1jKb6AiFOkS6uq8g)
  * :red_circle: run-python-rest-tests [#189](https://paste.fedoraproject.org/paste/Oj0mbTEZXQwr40UHM91DuA)
--------------

**Comment by gbaufake** [comment]
@mattmahoneyrh  and @hhovsepy  Tested and solves the problem
 `============================= test session starts ==============================
platform linux2 -- Python 2.7.15, pytest-3.4.1, py-1.5.2, pluggy-0.6.0
rootdir: /home/gbaufake/Redhat/kiali-qe-rest, inifile:
collected 10 items
tests/test_kiali_circuit_breakers.py                                    [ 10%]
tests/test_kiali_endpoint.py 
Get Kiali Client for Kiali hostname: kiali-istio-system.openshift2.jonqe.lab.eng.bos.redhat.com

.                                          [ 30%]
tests/test_kiali_route_rules.py 
Get Kiali Client for Kiali hostname: kiali-istio-system.openshift2.jonqe.lab.eng.bos.redhat.com

..                                        [ 40%]
tests/test_kiali_test_mesh.py .                                     [100%]

========================== 10 passed in 22.28 seconds ==========================......
Process finished with exit code 0
`

**Comment by gbaufake** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Build comment file: 
--------------
:heavy_check_mark: Jenkins CI: python-rest-test-pr [#10](https://paste.fedoraproject.org/paste/4DSNpLJGBEiYJ4A06Uqglw)
  * :heavy_check_mark: run-python-rest-tests [#192](https://paste.fedoraproject.org/paste/CPry5Wp2bC2MG9FTMN5qyQ)
--------------

**Pull request merged**
