### PR TITLE
Timeouts around waiting for RR to be created/deleted

### PR DESCRIPTION
**Pull request by mattmahoneyrh**

### CODE REVIEW

**Comment by hhovsepy** [comment]
@mattmahoneyrh yes this is the case that requirements are changed, but jenkins slaves are not updated.
So the solution here is that PR reviewer should test changes locally and merge the PR, then jenkins slaves should be immediately updated.

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by hhovsepy** [comment]
kialiqeci

**Comment by kialiqeci** [comment]
Build comment file: 
--------------
:red_circle: Jenkins CI: python-rest-test-pr [#6](https://paste.fedoraproject.org/paste/-KYmbtrf~FHi44D82-ti3w)
  * :red_circle: run-python-rest-tests [#185](https://paste.fedoraproject.org/paste/C0aPznnMNucxWXvTcPiM1A)
--------------

**Comment by kialiqeci** [comment]
Build comment file: 
--------------
:red_circle: Jenkins CI: python-rest-test-pr [#7](https://paste.fedoraproject.org/paste/Pvb~LM3p3LJCr15oeYB-yg)
  * :red_circle: run-python-rest-tests [#186](https://paste.fedoraproject.org/paste/~hbgTtO67nqlYlbccSziPA)
--------------

**Comment by mattmahoneyrh** [comment]
@hhovsepy this PR adds a new class utils.timeout, but no changes to requirements.txt which if was the case I would expect the jenkins agent to be rebuild (if that is your point). Thus, why would the jankins slave need to be rebuild in order for this branch to pass all tests when this PR includes the new  dependency?

**Pull request merged**
