### PR TITLE
[SWSQE-259] Adding README.md as minimal documentation

### LINKED ISSUE #24: Could you add some high level documentation?
@mattmahoneyrh @gbaufake Could you please add some high level documentation for this project?

* What it is doing?
* How to run it locally?

### PR DESCRIPTION
**Pull request by gbaufake**
This pull request closes #24.

### CODE REVIEW

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by gbaufake** [comment]
kialiqeci test

**Comment by kialiqeci** [comment]
!!! Couldn't read commit file !!!

**Comment by jkandasa** [comment]
@gbaufake LGTM :+1:

**Pull request merged**
