### PR TITLE
Added grapy-type tests

### PR DESCRIPTION
**Pull request by mattmahoneyrh**

### CODE REVIEW

**Comment by kialiqeci** [comment]
:red_circle: Jenkins CI: python-rest-test-pr [#45](https://paste.fedoraproject.org/paste/hVCDdKUOAzMiy15EUjYNNg)
  * :red_circle: run-python-rest-tests [#395](https://paste.fedoraproject.org/paste/nPBCOSB47ic75BPvs~jkIw)

**Comment by kialiqeci** [comment]
:heavy_check_mark: Jenkins CI: python-rest-test-pr [#46](https://paste.fedoraproject.org/paste/cBeHFaGMWc5hXsUSm86OrQ)

**Comment by kialiqeci** [comment]
:heavy_check_mark: Jenkins CI: python-rest-test-pr [#47](https://paste.fedoraproject.org/paste/JM-7Ugts0jwsfp2kCZHBNQ)

**Comment by mattmahoneyrh** [comment]
Note: The Jenkins failures were due to test class changes that were not yet reflected in the Jenkins job.

**Pull request merged**
